### ISSUE TITLE
Documentation of data input

### ISSUE THREAD

**Issue by lukkini** [ocbe-uio/EnrichIntersect#1]
Hello,
It would be very helpful to include documentation of how to format data input to use with this development.

Thanks

**Comment by wleoncio** [comment]
Hi @lukkini, thank you for your contribution!

Assuming your are talking about the `enrichment()` function, I agree documentation on version 0.6 can be a bit confusing. It states:

> x: a vector (matrix) of scores to be enriched
>
>custom.set: a self-defined set that summarizes a few groups of the
>         names (rownames) of ‘x’

From the function example, `x` is a matrix with rownames that match the "drug" column on `custom.set`.

`x` can also be just a vector. For example, using the objects in the function example, `enrichment(x[, 1], custom.set, permute.n = 2)` also works.

It could be helpful if you could provide us with a reproducible example of the data you're trying to use with the function, so we can improve the documentation to make the input procedure more clear.
